[workspace]
members = [".", "nginx-module"]

[package]
name = "codecrafters-interpreter"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[lib]
name = "lox"
path = "src/lib.rs"

[[bin]]
name = "codecrafters-interpreter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
thiserror = "1.0.38"                             # error handling

[dev-dependencies]
ureq = "3"                                       # HTTP-клиент для интеграционных тестов nginx
